name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test on Go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [ "1.9", "1.10", "1.11", "1.12" ]
        os: [ "ubuntu-latest", "windows-latest", "macOS-latest" ]
    services:
      mysql:
        image: mysql:8.0
        ports:
        - 3306:3306
        env:
          MYSQL_DATABASE: gotest
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: verysecret

    steps:

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out

    - name: vet
      run: go vet
